# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sieum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for sieum
    pod 'DBImageColorPicker', '~> 1.0.0'
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyBeaver'
    pod 'PopupDialog', '~> 0.5'
    pod 'SwiftyJSON'

  target 'sieumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sieumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SieumWidget' do
    pod 'Alamofire', '~> 4.3'
  end

end

